### ISSUE TITLE
Related Posts Title Shows Even With No Related Posts

### ISSUE THREAD

**Issue by bjcarlson42** [carlson-technologies/coffeeclass.io#58]
In the sidebar on any article, the related posts header shows even when there are no related posts.

**Comment by jayeclark** [comment]
I was hoping to help on this issue, but I'm having trouble replicating this issue. Has it maybe been fixed in a recent unlinked commit?

**Comment by bjcarlson42** [comment]
@jayeclark I fixed this is the following commit: https://github.com/carlson-technologies/coffeeclass.io/commit/ce0364cc3c7cfb42a0fdb3ca3b697dcf0a922c1d

Thanks for your interest in wanting to help! If you would like, check out the [roadmap](https://www.notion.so/benjamincarlson/609b8bb171844146a9bcd9fbabd171a8?v=341de17fff6149bea36dbafbe2f2cf88) to view new features that need coding! There are actually some issues (bugs) in there too. I will add them to GitHub issues soon.

**Comment by jayeclark** [comment]
Thanks! I took a quick look & have a fix for the get-headers bug if you'd like me to contribute that.

I also noticed some responsiveness issues at certain viewport widths (see screenshot below - content spills off the left side of the page between 1025 and 1133px viewport width) and also some console errors that are fairly easy to clean up, if you'd like someone external to take on those chores!

<img width="1050" alt="Screen Shot 2021-12-30 at 2 17 32 PM" src="https://user-images.githubusercontent.com/84106309/147784581-08f44794-9fe2-41ca-90ae-e1ca4bef2e04.png">

**Comment by bjcarlson42** [comment]
Any contributions are welcome (articles too)! Feel free to create a PR or even open your own issue!

**Comment by jayeclark** [comment]
I was just opening a draft PR as you were writing that (for the "get-headings gets md inside of code snippets" bug.) 🙂 

I think I can probably tackle issue #59 as well, since I've already been poking around in get-headings.ts and need to write unit tests for it already anyway.
